sudo: required
services:
  - docker

before_install: #build test version of client project and run tests inside of it
  - docker build -t react-test =f ./client/Dockerfile.dev ./client

script:
  - docker run react-test npm test -- --coverage

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker

#Login to docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#directing travis CLI to take these images and push to docker hub
- docker push multi-client
- docker push multi-nginx
- docker push multi-server
- docker push multi-worker
